spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://10.192.35.58:3308/dev_bms?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: root
    password: 123456
#    url: jdbc:mysql://192.168.99.100:3306/demo?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
#    username: root
#    password: 123456
  mvc:
    view:
      prefix: /
      suffix: .html

  redis:
      database: 0
      host: localhost
      port: 6379
      # 连接超时时间（毫秒）
      timeout: 60000
      password:
      # 连接池最大连接数（使用负值表示没有限制）
      pool:
        max-active: 200
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
      # 连接池中的最大空闲连接
        max-idle: 10
      # 连接池中的最小空闲连接
        min-idle: 0


server:
  port: 8082
  servlet:
    context-path: /cxs

mybatis-plus:
  mapper-locations: classpath*:mybatis/**/*.xml
  type-aliases-package: com.example.common.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

