spring:
  profiles:
    active: 201
  datasource:
    url: jdbc:mysql://192.168.99.100:32768/demo?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: root
    password: 123456
  mvc:
    view:
      prefix: /
      suffix: .html

server:
  port: 8082
  servlet:
    context-path: /cxs

mybatis:
  mapper-locations: classpath*:mybatis/**/*.xml