spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: root
    password: 123abc
  mvc:
    view:
      prefix: /
      suffix: .html

server:
  port: 8081
  servlet:
    context-path: /cxs

mybatis-plus:
  mapper-locations: classpath*:mybatis/**/*.xml
  type-aliases-package: com.example.common.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl