server:
  port: 8081
  servlet:
    context-path: /cxs


codeImg:
  path: D:/data/twoDimensionCode/
  save-zip-path: D:/data/codeImgZip/

aliyun:
  oss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    accessKeyId: LTAIoAyXiyPJPUKz
    secretAccessKey: QkO4zAsE0MeTWb2raO0yWkCW2E619Y
    bucketName: bmms-test-app


######## 短信
ums:
  sms:
    url: https://api.ums86.com:9600/sms/Api/Send.do
    spCode: 251743
    loginName: ed_cjdq
    password: cjdq2019



# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql